site_name: Khipo Docs
site_url: https://mb-data.github.io/
site_author: Arthur Olga, Filipe Borba
site_description: >-
  Repositório com documentações e materiais da Khipo

repo_name: khipo-docs
repo_url: https://github.com/mb-data/mb-data.github.io
edit_uri: "tree/main/docs"

theme:
  name: material
  favicon: assets/favicon.ico
  logo: https://khipo.com.br/wp-content/uploads/2019/09/khipologo.png

  features:
    - navigation.extend
  palette:
    # Light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: orange
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: orange
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes

nav:
  - Home: "index.md"
  - Testes de Software:
      - "Testes/Visão Geral.md"

extra_css:
  - ASCII_cinema/asciinema-player.css
  - _css/extra_css.css
extra_javascript:
  - ASCII_cinema/asciinema-player.js
  - _js/extra_js.js
